# Generated by Django 3.1.2 on 2020-10-15 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infobank', '0002_folder_parent_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infobank.department'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent_directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infobank.folder'),
        ),
    ]
