# Generated by Django 3.1.2 on 2020-10-15 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('infobank', '0003_auto_20201015_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='department',
        ),
        migrations.RemoveField(
            model_name='file',
            name='folder',
        ),
        migrations.AddField(
            model_name='file',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='file',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
