# Generated by Django 3.1.2 on 2020-10-15 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infobank', '0004_auto_20201015_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='file',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='file',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='department',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='infobank.folder'),
        ),
        migrations.AddField(
            model_name='folder',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AddField(
            model_name='folder',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infobank.category'),
        ),
    ]
