# Generated by Django 3.1.2 on 2020-10-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infobank', '0005_auto_20201015_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
