# Generated by Django 3.1.2 on 2020-10-18 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infobank', '0007_file_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='owner',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='owner',
            field=models.ManyToManyField(blank=True, related_name='folder_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infobank.folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folder_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folder',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
