# Generated by Django 3.1.2 on 2021-02-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infobank', '0011_auto_20210215_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'permissions': (('custom_file', 'Custom file'),)},
        ),
    ]
