# Generated by Django 3.1.2 on 2021-05-02 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infobank', '0013_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='group',
        ),
    ]
