# Generated by Django 3.1.2 on 2021-05-03 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infobank', '0014_remove_designation_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Designation',
        ),
    ]
